//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Omra
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bizonyitekok
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bizonyitekok()
        {
            this.FelvettBizonyitekok = new HashSet<FelvettBizonyitekok>();
        }
    
        public decimal bizonyitekID { get; set; }
        public string megnevezes { get; set; }
        public System.DateTime felvetel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FelvettBizonyitekok> FelvettBizonyitekok { get; set; }
    }
}
