///////////////////////////////////////////////////////////
//  Bizonyíték.cs
//  Implementation of the Class Bizonyíték
//  Generated by Enterprise Architect
//  Created on:      02-ápr.-2016 10:16:28
//  Original author: Dániel
///////////////////////////////////////////////////////////




using System;
namespace Adatkezelõ {
	public class Bizonyíték {

		private string azonosító;
		/// <summary>
		/// pl. kés, pisztoly stb.
		/// </summary>
		private string megnevezés;

        private DateTime felvetel;
        
		/// 
		/// <param name="megnevezés"></param>
		/// <param name="azonosító"></param>
		public Bizonyíték(string megnevezés, string azonosító, DateTime felvetel){
            this.megnevezés = megnevezés;
            this.azonosító = azonosító;
            this.felvetel = felvetel;
		}

		public string GetAzonosító{
			get{
				return azonosító;
			}
			set{
				azonosító = value;
			}
		}

		public string GetMegnevezés(){

			return this.megnevezés;
		}

        public DateTime Felvetel()
        {
            return this.felvetel;
        }

        public override string ToString()
        {
            return "ID " + azonosító + " Megnevezés: " + megnevezés + " Felvétel: " + felvetel;
        }
	}//end Bizonyíték

}//end namespace Adatkezelõ