///////////////////////////////////////////////////////////
//  Bizonyíték.cs
//  Implementation of the Class Bizonyíték
//  Generated by Enterprise Architect
//  Created on:      02-ápr.-2016 10:16:28
//  Original author: Dániel
///////////////////////////////////////////////////////////




namespace Adatkezelõ {
	public class Bizonyíték {

		private string azonosító;
		/// <summary>
		/// pl. kés, pisztoly stb.
		/// </summary>
		private string megnevezés;
        
		/// 
		/// <param name="megnevezés"></param>
		/// <param name="azonosító"></param>
		public Bizonyíték(string megnevezés, string azonosító){
            this.megnevezés = megnevezés;
            this.azonosító = azonosító;
		}

		public string GetAzonosító{
			get{
				return azonosító;
			}
			set{
				azonosító = value;
			}
		}

		public string GetMegnevezés(){

			return this.megnevezés;
		}

	}//end Bizonyíték

}//end namespace Adatkezelõ