///////////////////////////////////////////////////////////
//  Bizonyíték.cs
//  Implementation of the Class Bizonyíték
//  Generated by Enterprise Architect
//  Created on:      02-ápr.-2016 10:16:28
//  Original author: Dániel
///////////////////////////////////////////////////////////




using System;
namespace Adatkezelõ {
	public class Bizonyíték {

		private decimal azonosító;
		/// <summary>
		/// pl. kés, pisztoly stb.
		/// </summary>
        public string Megnevezés { get; set; }

        private DateTime felvetel;
        
		/// 
		/// <param name="megnevezés"></param>
		/// <param name="azonosító"></param>
        public Bizonyíték(decimal azonosító, string megnevezés, DateTime felvetel)
        {
            this.Megnevezés = megnevezés;
            this.azonosító = azonosító;
            this.felvetel = felvetel;
		}

		public decimal GetAzonosító{
			get{
				return azonosító;
			}
			set{
				azonosító = value;
			}
		}


        public DateTime Felvetel()
        {
            return this.felvetel;
        }

        public override string ToString()
        {
            return "ID " + azonosító + " Megnevezés: " + Megnevezés + " Felvétel: " + felvetel;
        }
	}//end Bizonyíték

}//end namespace Adatkezelõ