///////////////////////////////////////////////////////////
//  BÁllapot.cs
//  Implementation of the Class BÁllapot
//  Generated by Enterprise Architect
//  Created on:      02-ápr.-2016 10:16:28
//  Original author: Dániel
///////////////////////////////////////////////////////////




namespace Adatkezelõ {
	public enum BÁllapot : int {

		Lezárt,
		Folyamatban

	}//end BÁllapot

}//end namespace Adatkezelõ