///////////////////////////////////////////////////////////
//  Bûneset.cs
//  Implementation of the Class Bûneset
//  Generated by Enterprise Architect
//  Created on:      02-ápr.-2016 10:16:28
//  Original author: Dániel
///////////////////////////////////////////////////////////




using Adatkezelõ;
using System;
using System.Collections.Generic;
namespace Adatkezelõ {
	public class Bûneset 
    {

		private string azonosító;

		private BÁllapot állapot;

        private DateTime felvetel;
        private DateTime lezaras;

        private string leiras;
        
		/// 
		/// <param name="azonosító"></param>
		public Bûneset(string azonosító, string leiras){   //felvételhez
            this.azonosító = azonosító;

            this.állapot = BÁllapot.Folyamatban;
            this.felvetel = DateTime.Now;
            this.leiras = leiras;
		}

        public Bûneset(string azonosító, BÁllapot allapot, DateTime felvetel, string leiras)  //megjelenítéshez a keresésben
        {
            this.azonosító = azonosító;
            this.állapot = allapot;
            this.felvetel = felvetel;
            this.leiras = leiras;
        }

		public void Állapotmódosítás()
        {
            if (állapot == BÁllapot.Folyamatban)
            {
                állapot = BÁllapot.Lezárt;
                this.lezaras = DateTime.Now;
            }
            if (állapot == BÁllapot.Lezárt)
            {
                állapot = BÁllapot.Folyamatban;
                //lezaras = null    //datetime nem nullázható -> mivel legyen jelölve?
            }
		}

		/// 
		/// <param name="Bûneset"></param>
		/// <param name="Bizonyíték"></param>
		public void BizonyítékHozzáadása(Bûneset Bûneset, Bizonyíték Bizonyíték){
            
		}

		public BÁllapot GetÁllapot(){

            return this.állapot;
		}

		public string GetAzonosító{
			get
            {
				return azonosító;
			}
		}

        public DateTime GetFelvetel
        {
            get
            {
                return felvetel;
            }
        }

        public DateTime GetLezaras
        {
            get
            {
                return lezaras;
            }
        }

        public string GetLeiras
        {
            get
            {
                return leiras;
            }
        }

		/// 
		/// <param name="Gyanúsított"></param>
		public void GyanúsítottHozzáadása(Gyanúsított Gyanúsított){
            
		}

        public override string ToString()
        {
            return "ID:" + azonosító + " Állapot: " + állapot.ToString() + " Felvétel: " + felvetel.ToShortDateString() + "\n Leírás: " + leiras;
        }

	}//end Bûneset

}//end namespace Adatkezelõ