///////////////////////////////////////////////////////////
//  BûnesetiKimutatás.cs
//  Implementation of the Class BûnesetiKimutatás
//  Generated by Enterprise Architect
//  Created on:      02-ápr.-2016 10:16:28
//  Original author: hallgato
///////////////////////////////////////////////////////////




using Adatkezelõ;
namespace Adatkezelõ {
	public class BûnesetiKimutatás : Kimutatás {

		private List<Bizonyíték> bizonyítékok;
		private List<Bûneset> bûnesetek;
		private List<Gyanúsított> gyanúsítottak;

		public BûnesetiKimutatás(){

		}

		~BûnesetiKimutatás(){

		}

		public override void Dispose(){

		}

		public List<Bizonyíték> GetBizonyítékok(){

			return null;
		}

		public List<Bûneset> GetBûnesetek(){

			return null;
		}

		public List<Gyanúsított> GetGyanúsítottak(){

			return null;
		}

		/// 
		/// <param name="kezdet"></param>
		/// <param name="vege"></param>
		public void ÚjBûnesetiKimutatás(DateTime kezdet, DateTime vege){

		}

	}//end BûnesetiKimutatás

}//end namespace Adatkezelõ