///////////////////////////////////////////////////////////
//  Bûneset.cs
//  Implementation of the Class Bûneset
//  Generated by Enterprise Architect
//  Created on:      02-ápr.-2016 10:16:28
//  Original author: Dániel
///////////////////////////////////////////////////////////




using Adatkezelõ;
using System.Collections.Generic;
namespace Adatkezelõ {
	public class Bûneset {

		private string azonosító;
		private List<Dolgozó> dolgozók;
		private List<Gyanúsított> gyanúsítottak;
		private Bizonyíték bizonyítékok;
		private BÁllapot állapot;

		public Bûneset(){

		}

		~Bûneset(){

		}

		public virtual void Dispose(){

		}

		/// 
		/// <param name="azonosító"></param>
		public Bûneset(string azonosító){

		}

		public void Állapotmódosítás(){

		}

		/// 
		/// <param name="Bûneset"></param>
		/// <param name="Bizonyíték"></param>
		public void BizonyítékHozzáadása(Bûneset Bûneset, Bizonyíték Bizonyíték){

		}

		public BÁllapot GetÁllapot(){

			return null;
		}

		public string GetAzonosító{
			get{
				return azonosító;
			}
			set{
				azonosító = value;
			}
		}

		public List<Bizonyíték> GetBizonyítékok(){

			return null;
		}

		public List<Gyanúsított> GetGyanúsítottak(){

			return null;
		}

		/// 
		/// <param name="Gyanúsított"></param>
		public void GyanúsítottHozzáadása(Gyanúsított Gyanúsított){

		}

	}//end Bûneset

}//end namespace Adatkezelõ