//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Omra
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dolgozok
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dolgozok()
        {
            this.Bunesetek = new HashSet<Bunesetek>();
            this.FelvettDolgozok = new HashSet<FelvettDolgozok>();
            this.Uzenetek = new HashSet<Uzenetek>();
            this.Uzenetek1 = new HashSet<Uzenetek>();
        }
    
        public decimal dolgozoID { get; set; }
        public string nev { get; set; }
        public string lakcim { get; set; }
        public string jelszo { get; set; }
        public string rang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bunesetek> Bunesetek { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FelvettDolgozok> FelvettDolgozok { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Uzenetek> Uzenetek { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Uzenetek> Uzenetek1 { get; set; }
    }
}
