///////////////////////////////////////////////////////////
//  Dolgozó.cs
//  Implementation of the Class Dolgozó
//  Generated by Enterprise Architect
//  Created on:      02-ápr.-2016 10:16:28
//  Original author: gabi1_000
///////////////////////////////////////////////////////////




using Adatkezelõ;
namespace Adatkezelõ {
	public class Dolgozó : Személy {

		private string jelszó;
		private Rang beosztás;
        
		public Dolgozó(Rang Rang, string jelszó, string név, string lakcím, decimal személyiazonosító)
            :base(személyiazonosító,lakcím,név)
        {
            this.beosztás = Rang;
            this.jelszó = jelszó;
		}

		public Rang GetBeosztás(){

            return beosztás;
		}

		public string GetJelszó(){
            return jelszó;
		}

        public override string ToString()
        {
            return this.név + " (" + this.beosztás.ToString() + ")";
        }

	}//end Dolgozó

}//end namespace Adatkezelõ