///////////////////////////////////////////////////////////
//  Dolgozó.cs
//  Implementation of the Class Dolgozó
//  Generated by Enterprise Architect
//  Created on:      02-ápr.-2016 10:16:28
//  Original author: gabi1_000
///////////////////////////////////////////////////////////




using Adatkezelõ;
namespace Adatkezelõ {
	public class Dolgozó : Személy {

		private string jelszó;
		private Rang beosztás;
        
		/// 
		/// <param name="Rang"></param>
		/// <param name="jelszó"></param>
		/// <param name="név"></param>
		/// <param name="lakcím"></param>
		/// <param name="személyiazonosító"></param>
		public Dolgozó(Rang Rang, string jelszó, string név, string lakcím, string személyiazonosító)
            :base(személyiazonosító,lakcím,név)
        {
            this.beosztás = Rang;
            this.jelszó = jelszó;
		}

		public Rang GetBeosztás(){

            return beosztás;
		}

		public string GetJelszó(){
            return jelszó;
		}

	}//end Dolgozó

}//end namespace Adatkezelõ