///////////////////////////////////////////////////////////
//  Feladatkezelõ.cs
//  Implementation of the Class Feladatkezelõ
//  Generated by Enterprise Architect
//  Created on:      02-ápr.-2016 10:16:28
//  Original author: Dániel
///////////////////////////////////////////////////////////




using Adatkezelõ;
using System.Collections.Generic;
namespace Adatkezelõ {
	public class Feladatkezelõ : IFeladatkezelõ {

		private List<Feladat> feladatok;
        
		/// 
		/// <param name="feladat"></param>
		public void FeladatÁllapotMódosítás(Feladat feladat){

		}

		/// 
		/// <param name="Dolgozó"></param>
		public List<Feladat> FeladatokLekérdezése(Dolgozó Dolgozó){

			return this.feladatok;
		}

		/// 
		/// <param name="célszemély"></param>
		/// <param name="létrehozta"></param>
		/// <param name="leírás"></param>
		public void ÚjFeladat(Dolgozó célszemély, Dolgozó létrehozta, string leírás){
            Feladat f = new Feladat(leírás, célszemély , létrehozta);
            this.feladatok.Add(f);
		}



        List<Feladat> IFeladatkezelõ.FeladatokLekérdezése(Dolgozó Dolgozó)
        {
            throw new System.NotImplementedException();
        }
    }//end Feladatkezelõ

}//end namespace Adatkezelõ