///////////////////////////////////////////////////////////
//  Feladat.cs
//  Implementation of the Class Feladat
//  Generated by Enterprise Architect
//  Created on:      02-ápr.-2016 10:16:28
//  Original author: Dániel
///////////////////////////////////////////////////////////




using Adatkezelõ;
namespace Adatkezelõ {
	public class Feladat {

		/// <summary>
		/// Akinek a feladat szól
		/// </summary>
		private Dolgozó célszemély;
		private string leírás;
		/// <summary>
		/// Ki adta ki a feladatot
		/// </summary>
		private Dolgozó létrehozta;
		private FÁllapot állapot;

		public Feladat(){

		}

		~Feladat(){

		}

		public virtual void Dispose(){

		}

		/// 
		/// <param name="leírás"></param>
		/// <param name="célszemély"></param>
		/// <param name="létrehozó"></param>
		public Feladat(string leírás, Dolgozó célszemély, Dolgozó létrehozó){

		}

		/// <summary>
		/// Akinek a feladat szól
		/// </summary>
		public Dolgozó GetCélszemély{
			get{
				return célszemély;
			}
			set{
				célszemély = value;
			}
		}

		public string GetLeírás{
			get{
				return leírás;
			}
			set{
				leírás = value;
			}
		}

		/// <summary>
		/// Ki adta ki a feladatot
		/// </summary>
		public Dolgozó GetLétrehozta{
			get{
				return létrehozta;
			}
			set{
				létrehozta = value;
			}
		}

	}//end Feladat

}//end namespace Adatkezelõ