///////////////////////////////////////////////////////////
//  Feladat.cs
//  Implementation of the Class Feladat
//  Generated by Enterprise Architect
//  Created on:      02-ápr.-2016 10:16:28
//  Original author: Dániel
///////////////////////////////////////////////////////////




using Adatkezelõ;
using System;
namespace Adatkezelõ {
	public class Feladat {

		/// <summary>
		/// Akinek a feladat szól
		/// </summary>
		private Dolgozó célszemély;
		private string leírás;
		private FÁllapot állapot;
        private decimal feladatID;
        /// <summary>
        /// Amikor a bûneset létre lett hozva
        /// </summary>
        private DateTime létrehozás;
        
		/// 
		/// <param name="leírás"></param>
		/// <param name="célszemély"></param>
		/// <param name="létrehozó"></param>
		public Feladat(string leírás, Dolgozó célszemély, DateTime létrehozás,FÁllapot állapot)
        {
            this.leírás = leírás;
            this.célszemély = célszemély;
            this.állapot = állapot;
            this.létrehozás = létrehozás;
		}

		/// <summary>
		/// Akinek a feladat szól
		/// </summary>
		public Dolgozó GetCélszemély
        {
            get { return célszemély; }
            set { célszemély = value; }
		}

		public string GetLeírás{
            get { return leírás; }
            set { leírás = value; }
		}
        
        public decimal GetFeladatID
        {
            get { return feladatID; }
            set { feladatID = value; }
        }

        public DateTime GetLétrehozás
        {
            get { return létrehozás; }
            set { létrehozás = value; }
        }

        public FÁllapot GetÁllapot
        {
            get { return állapot; }
            set { állapot = value; }
        }
        
        public override string ToString()
        {
            if (this.leírás.Length > 30)
                return this.leírás.Substring(0, 30) + "...";
            return this.leírás;
        }

	}//end Feladat

}//end namespace Adatkezelõ