///////////////////////////////////////////////////////////
//  Feladatkezelõ.cs
//  Implementation of the Class Feladatkezelõ
//  Generated by Enterprise Architect
//  Created on:      02-ápr.-2016 10:16:28
//  Original author: Dániel
///////////////////////////////////////////////////////////




using Adatkezelõ;
using Omra;
using System;
using System.Collections.Generic;
using System.Linq;
namespace Adatkezelõ {
	public class Feladatkezelõ : IFeladatkezelõ {

        DatabaseElements DE = new DatabaseElements();
        
		/// 
		/// <param name="feladat"></param>
		public void FeladatÁllapotMódosítás(Feladat feladat){

		}

		/// 
		/// <param name="célszemély"></param>
		/// <param name="létrehozta"></param>
		/// <param name="leírás"></param>
		public void ÚjFeladat(Dolgozó célszemély, Dolgozó létrehozta, string leírás){
            //Feladat f = new Feladat(leírás, célszemély , létrehozta);
            //this.feladatok.Add(f);
		}

        List<Feladat> IFeladatkezelõ.FeladatokLekérdezése(Dolgozó dolgozo)
        {
            decimal id = dolgozo.GetAzonosító();    // linq nem szereti ha ott kérem el
            List<Feladat> vissza = new List<Feladat>();
            var uzenetek = from x in DE.Bunesetek
                           where x.Dolgozok.dolgozoID == id
                           select x;
            foreach (var item in uzenetek)
            {
                vissza.Add(new Feladat(item.leiras, dolgozo, dolgozo));
            }
            return vissza;
        }
    }//end Feladatkezelõ

}//end namespace Adatkezelõ