///////////////////////////////////////////////////////////
//  FÁllapot.cs
//  Implementation of the Class FÁllapot
//  Generated by Enterprise Architect
//  Created on:      02-ápr.-2016 10:16:28
//  Original author: Dániel
///////////////////////////////////////////////////////////




namespace Adatkezelõ {
	public enum FÁllapot : int {

		Folyamatban,
		Befejezve

	}//end FÁllapot

}//end namespace Adatkezelõ