///////////////////////////////////////////////////////////
//  Gyanúsított.cs
//  Implementation of the Class Gyanúsított
//  Generated by Enterprise Architect
//  Created on:      02-ápr.-2016 10:16:28
//  Original author: gabi1_000
///////////////////////////////////////////////////////////




using Adatkezelõ;
namespace Adatkezelõ {
	public class Gyanúsított : Személy {



		protected GyanúsítottStátusz státusz;
        
		public Gyanúsított(GyanúsítottStátusz státusz, string név, string lakcím, decimal személyiazonosító)
            :base(személyiazonosító,lakcím,név)
        {
            this.státusz = státusz;
		}

		public GyanúsítottStátusz GetStátusz(){

			return this.státusz;
		}


        public override string ToString()
        {
            return "ID: " + this.azonosító + " Név: " + this.név + " Státusz: " + this.státusz.ToString();
        }
	}//end Gyanúsított

}//end namespace Adatkezelõ