///////////////////////////////////////////////////////////
//  Gyanúsított.cs
//  Implementation of the Class Gyanúsított
//  Generated by Enterprise Architect
//  Created on:      02-ápr.-2016 10:16:28
//  Original author: gabi1_000
///////////////////////////////////////////////////////////




using Adatkezelõ;
namespace Adatkezelõ {
	public class Gyanúsított : Személy {

		private GyanúsítottStátusz státusz;

		public Gyanúsított(){

		}

		~Gyanúsított(){

		}

		public override void Dispose(){

		}

		/// 
		/// <param name="státusz"></param>
		/// <param name="név"></param>
		/// <param name="lakcím"></param>
		/// <param name="személyiazonosító"></param>
		public Gyanúsított(GyanúsítottStátusz státusz, string név, string lakcím, string személyiazonosító){

		}

		public GyanúsítottStátusz GetStátusz(){

			return null;
		}

	}//end Gyanúsított

}//end namespace Adatkezelõ