///////////////////////////////////////////////////////////
//  Gyanúsított.cs
//  Implementation of the Class Gyanúsított
//  Generated by Enterprise Architect
//  Created on:      02-ápr.-2016 10:16:28
//  Original author: gabi1_000
///////////////////////////////////////////////////////////




using Adatkezelõ;
namespace Adatkezelõ {
	public class Gyanúsított : Személy {

        private string név;
        private string bejelentettLakcím;
        private string azonosító;
		private GyanúsítottStátusz státusz;
        
		/// 
		/// <param name="státusz"></param>
		/// <param name="név"></param>
		/// <param name="lakcím"></param>
		/// <param name="személyiazonosító"></param>
		public Gyanúsított(GyanúsítottStátusz státusz, string név, string lakcím, decimal személyiazonosító)
            :base(személyiazonosító,lakcím,név)
        {
            this.státusz = státusz;
		}

		public GyanúsítottStátusz GetStátusz(){

			return this.státusz;
		}

	}//end Gyanúsított

}//end namespace Adatkezelõ