///////////////////////////////////////////////////////////
//  GyanúsítottStátusz.cs
//  Implementation of the Class GyanúsítottStátusz
//  Generated by Enterprise Architect
//  Created on:      02-ápr.-2016 10:16:28
//  Original author: gabi1_000
///////////////////////////////////////////////////////////




namespace Adatkezelõ {
	public enum GyanúsítottStátusz : int {

		Szabad,
		Elozetesben,
		Letartóztatott

	}//end GyanúsítottStátusz

}//end namespace Adatkezelõ