///////////////////////////////////////////////////////////
//  GYÁllapot.cs
//  Implementation of the Class GYÁllapot
//  Generated by Enterprise Architect
//  Created on:      02-ápr.-2016 10:16:28
//  Original author: Dániel
///////////////////////////////////////////////////////////




namespace Adatkezelõ {
	public enum GYÁllapot : int {

		Szabad,
		Elõzetesben,
		Letartóztatott

	}//end GYÁllapot

}//end namespace Adatkezelõ