///////////////////////////////////////////////////////////
//  IBizonyítékkezelõ.cs
//  Implementation of the Interface IBizonyítékkezelõ
//  Generated by Enterprise Architect
//  Created on:      02-ápr.-2016 10:16:28
//  Original author: Dániel
///////////////////////////////////////////////////////////




namespace Adatkezelõ {
	public interface IBizonyítékkezelõ {

		/// 
		/// <param name="bizonyíték">ez kérdéses</param>
		/// <param name="bûneset"></param>
		void BizonyítékHozzáadása(Bizonyíték bizonyíték, Bûneset bûneset);

		/// 
		/// <param name="megnevezés">Mint pl. kés, pisztoly stb.</param>
		void ÚjBizonyíték(string megnevezés);
	}//end IBizonyítékkezelõ

}//end namespace Adatkezelõ