///////////////////////////////////////////////////////////
//  IBûnesetkezelõ.cs
//  Implementation of the Interface IBûnesetkezelõ
//  Generated by Enterprise Architect
//  Created on:      02-ápr.-2016 10:16:28
//  Original author: Dániel
///////////////////////////////////////////////////////////




namespace Adatkezelõ {
	public interface IBûnesetkezelõ {

		/// 
		/// <param name="Bûneset"></param>
		void BûnesetÁllapotmódosítás(Bûneset Bûneset);

		/// 
		/// <param name="Gyanúsított"></param>
		/// <param name="Bûneset"></param>
		void GyanúsítottHozzáadása(Gyanúsított Gyanúsított, Bûneset Bûneset);

		void ÚjBûneset();
	}//end IBûnesetkezelõ

}//end namespace Adatkezelõ