///////////////////////////////////////////////////////////
//  IBûnesetkezelõ.cs
//  Implementation of the Interface IBûnesetkezelõ
//  Generated by Enterprise Architect
//  Created on:      02-ápr.-2016 10:16:28
//  Original author: Dániel
///////////////////////////////////////////////////////////




using System;
namespace Adatkezelõ {
	public interface IBûnesetkezelõ {

		/// 
		/// <param name="Bûneset"></param>
		BÁllapot BûnesetÁllapotmódosítás(Bûneset Bûneset);

		/// 
		/// <param name="Gyanúsított"></param>
		/// <param name="Bûneset"></param>
		void GyanúsítottHozzáadása(Gyanúsított Gyanúsított, Bûneset Bûneset);

		void ÚjBûneset(decimal azon,string allapot, DateTime felvetel, string leiras, decimal felOrnagyId);
	}//end IBûnesetkezelõ

}//end namespace Adatkezelõ