///////////////////////////////////////////////////////////
//  IDolgozókezelõ.cs
//  Implementation of the Interface IDolgozókezelõ
//  Generated by Enterprise Architect
//  Created on:      02-ápr.-2016 10:16:28
//  Original author: gabi1_000
///////////////////////////////////////////////////////////




using Adatkezelõ;
namespace Adatkezelõ {
	public interface IDolgozókezelõ {

		/// 
		/// <param name="azonosító"></param>
		/// <param name="jelszó"></param>
		Dolgozó Azonosítás(string azonosító, string jelszó);

		/// 
		/// <param name="dolgozó"></param>
		void DolgozóMódosítása(Dolgozó dolgozó);

		/// 
		/// <param name="Dolgozó"></param>
		void DolgozóTörlése(Dolgozó Dolgozó);

		/// 
		/// <param name="jelszó"></param>
		/// <param name="beosztás"></param>
		/// <param name="név"></param>
		/// <param name="azonosító"></param>
		/// <param name="lakcím"></param>
		void ÚjDolgozó(string jelszó, Rang beosztás, string név, decimal azonosító, string lakcím);
	}//end IDolgozókezelõ

}//end namespace Adatkezelõ