///////////////////////////////////////////////////////////
//  IFeladatkezelõ.cs
//  Implementation of the Interface IFeladatkezelõ
//  Generated by Enterprise Architect
//  Created on:      02-ápr.-2016 10:16:28
//  Original author: Dániel
///////////////////////////////////////////////////////////




using Adatkezelõ;
using System.Collections.Generic;
namespace Adatkezelõ {
	public interface IFeladatkezelõ {
        
		/// 
		/// <param name="Dolgozó"></param>
		List<Feladat> FeladatokLekérdezése(Dolgozó dolgozo);

        /// 
        /// <param name="Dolgozó"></param>
        /// <param name="Bûneset"></param>
        void FeladatMentés(Dolgozó célszemély, Bûneset bûneset);

	}//end IFeladatkezelõ

}//end namespace Adatkezelõ