///////////////////////////////////////////////////////////
//  IFeladatkezelõ.cs
//  Implementation of the Interface IFeladatkezelõ
//  Generated by Enterprise Architect
//  Created on:      02-ápr.-2016 10:16:28
//  Original author: Dániel
///////////////////////////////////////////////////////////




using Adatkezelõ;
using System.Collections.Generic;
namespace Adatkezelõ {
	public interface IFeladatkezelõ {

		/// 
		/// <param name="feladat"></param>
		void FeladatÁllapotMódosítás(Feladat feladat);

		/// 
		/// <param name="Dolgozó"></param>
		List<Feladat> FeladatokLekérdezése(Dolgozó dolgozo);

		/// 
		/// <param name="célszemély"></param>
		/// <param name="létrehozta"></param>
		/// <param name="leírás"></param>
		void ÚjFeladat(Dolgozó célszemély, Dolgozó létrehozta, string leírás);
	}//end IFeladatkezelõ

}//end namespace Adatkezelõ