///////////////////////////////////////////////////////////
//  IGyanúsítottkezelõ.cs
//  Implementation of the Interface IGyanúsítottkezelõ
//  Generated by Enterprise Architect
//  Created on:      02-ápr.-2016 10:16:28
//  Original author: Dániel
///////////////////////////////////////////////////////////




using Adatkezelõ;
namespace Adatkezelõ {
	public interface IGyanúsítottkezelõ {

		/// 
		/// <param name="gyanúsított"></param>
		/// <param name="bûneset"></param>
		void GyanúsítottHozzáadása(Gyanúsított gyanúsított, Bûneset bûneset);

		/// 
		/// <param name="gyanúsított"></param>
		void GyanúsítottMódosítása(Gyanúsított gyanúsított);

		/// 
		/// <param name="gyanúsítottStátusz"></param>
		/// <param name="lakcím"></param>
		/// <param name="személyiAzonosító"></param>
		/// <param name="név"></param>
		void ÚjGyanúsított(GyanúsítottStátusz gyanúsítottStátusz, string lakcím, string személyiAzonosító, string név);
	}//end IGyanúsítottkezelõ

}//end namespace Adatkezelõ