///////////////////////////////////////////////////////////
//  IKereséskezelõ.cs
//  Implementation of the Interface IKereséskezelõ
//  Generated by Enterprise Architect
//  Created on:      02-ápr.-2016 10:16:29
//  Original author: Dániel
///////////////////////////////////////////////////////////




using Adatkezelõ;
using System.Collections.Generic;
namespace Adatkezelõ {

    public enum KeresésTípus { Bûneset, Gyanúsított, Bizonyíték, Dolgozó }
	public interface IKereséskezelõ {

		/// 
		/// <param name="azonosító"></param>
		Bizonyíték Bizonyítékkeresés(string azonosító);

		/// 
		/// <param name="azonosító"></param>
		Bûneset Bûnesetkeresés(string azonosító);

		/// 
		/// <param name="azonosito"></param>
		Dolgozó Dolgozókeresés(string azonosito);

		/// 
		/// <param name="azonosító"></param>
		Gyanúsított Gyanúsítottkeresés(string azonosító);

		/// 
		/// <param name="azonosító"></param>
		/// <param name="típus"></param>
		List<object> Keresés(string azonosító, KeresésTípus típus);
	}//end IKereséskezelõ

}//end namespace Adatkezelõ