///////////////////////////////////////////////////////////
//  IKimutatáskezelõ.cs
//  Implementation of the Interface IKimutatáskezelõ
//  Generated by Enterprise Architect
//  Created on:      02-ápr.-2016 10:16:29
//  Original author: hallgato
///////////////////////////////////////////////////////////



using System;

namespace Adatkezelõ 
{
	public interface IKimutatáskezelõ 
    {

		/// 
		/// <param name="kezdet"></param>
		/// <param name="vege"></param>
		void ÚjKimutatás(DateTime kezdet, DateTime vege);
	}//end IKimutatáskezelõ

}//end namespace Adatkezelõ