///////////////////////////////////////////////////////////
//  IÜzenetkezelõ.cs
//  Implementation of the Interface IÜzenetkezelõ
//  Generated by Enterprise Architect
//  Created on:      02-ápr.-2016 10:16:29
//  Original author: Dániel
///////////////////////////////////////////////////////////




using Adatkezelõ;
namespace Adatkezelõ {
	public interface IÜzenetkezelõ {

		/// 
		/// <param name="törzs"></param>
		/// <param name="tárgy"></param>
		/// <param name="küldõ"></param>
		/// <param name="címzett"></param>
		void ÜzenetKüldése(string törzs, string tárgy, Dolgozó küldõ, Dolgozó címzett);

		/// 
		/// <param name="Dolgozó"></param>
		List<Üzenet> ÜzenetMegtekintése(Dolgozó Dolgozó);

		/// 
		/// <param name="üzenet"></param>
		void ÜzenetTörlése(Üzenet üzenet);
	}//end IÜzenetkezelõ

}//end namespace Adatkezelõ