///////////////////////////////////////////////////////////
//  Kereséskezelõ.cs
//  Implementation of the Class Kereséskezelõ
//  Generated by Enterprise Architect
//  Created on:      02-ápr.-2016 10:16:29
//  Original author: Dániel
///////////////////////////////////////////////////////////




using Adatkezelõ;
using System.Collections.Generic;
namespace Adatkezelõ {
	public class Kereséskezelõ : IKereséskezelõ, IKereséskezelõ {

		public Kereséskezelõ(){

		}

		~Kereséskezelõ(){

		}

		public virtual void Dispose(){

		}

		/// 
		/// <param name="azonosító"></param>
		public Bizonyíték Bizonyítékkeresés(string azonosító){

			return null;
		}

		/// 
		/// <param name="azonosító"></param>
		public Bûneset Bûnesetkeresés(string azonosító){

			return null;
		}

		/// 
		/// <param name="azonosito"></param>
		public Dolgozó Dolgozókeresés(string azonosito){

			return null;
		}

		/// 
		/// <param name="azonosító"></param>
		/// <param name="típus"></param>
		public List<object> Keresés(string azonosító, KeresésTípus típus){

			return null;
		}

		/// 
		/// <param name="azonosító"></param>
		public Gyanúsított Gyanúsítottkeresés(string azonosító){

			return null;
		}

	}//end Kereséskezelõ

}//end namespace Adatkezelõ