///////////////////////////////////////////////////////////
//  Kimutatáskészítõ.cs
//  Implementation of the Class Kimutatáskészítõ
//  Generated by Enterprise Architect
//  Created on:      02-ápr.-2016 10:16:29
//  Original author: hallgato
///////////////////////////////////////////////////////////



using Omra;
using Adatkezelõ;
using System;
using System.Linq;
using System.Collections.Generic;
namespace Adatkezelõ {
	public class Kimutatáskészítõ
    {
        private KimutatasTipus tipus;
		private Kimutatás kimutatás;
        
		public Kimutatás GetKimutatás(){
			return this.kimutatás;
		}

        public KimutatasTipus GetKimutatásTípus()
        {
            return this.tipus;
        }

        public Kimutatáskészítõ(DateTime kezdet, DateTime vege, KimutatasTipus tipus)
        {
            this.kimutatás = new Kimutatás(vege, kezdet);
            this.tipus = tipus;
        }

        public List<Bizonyíték> GetBizonyítékok()
        {
            //adott intervallumban levõ bûnesetek id-jai
            var ids = from x in this.kimutatás.GetAdatok
                      select x.GetAzonosító;

            //felvett tábla alapján a bizonyítékok kikeresése
                        //...       
            throw new NotImplementedException();
        }
    }//end Kimutatáskészítõ

}//end namespace Adatkezelõ