///////////////////////////////////////////////////////////
//  Kimutatás.cs
//  Implementation of the Class Kimutatás
//  Generated by Enterprise Architect
//  Created on:      02-ápr.-2016 10:16:29
//  Original author: hallgato
///////////////////////////////////////////////////////////




using System;
using System.Collections.Generic;
namespace Adatkezelõ {
	public class Kimutatás:IKimutatáskezelõ 
    {
		protected DateTime kezdet;
		protected DateTime vege;
        private List<int> statAdatok;

		/// 
		/// <param name="vege"></param>
		/// <param name="kezdet"></param>
		public Kimutatás(DateTime vege, DateTime kezdet)
        {
            this.vege = vege;
            this.kezdet = kezdet;
            statAdatok = new List<int>();
		}

        public void ÚjKimutatás(DateTime vege, DateTime kezdet)
        {
 	        throw new NotImplementedException();
            // linq val összegyûjti az adatokat a listába
            // 
        }

    }//end Kimutatás

}//end namespace Adatkezelõ