///////////////////////////////////////////////////////////
//  Rang.cs
//  Implementation of the Class Rang
//  Generated by Enterprise Architect
//  Created on:      02-ápr.-2016 10:16:29
//  Original author: gabi1_000
///////////////////////////////////////////////////////////




namespace Adatkezelõ {
	public enum Rang : int {

		Tiszt,
		Õrnagy,
		Kapitány,
		Adminisztrátor

	}//end Rang

}//end namespace Adatkezelõ