///////////////////////////////////////////////////////////
//  Személy.cs
//  Implementation of the Class Személy
//  Generated by Enterprise Architect
//  Created on:      02-ápr.-2016 10:16:29
//  Original author: gabi1_000
///////////////////////////////////////////////////////////




namespace Adatkezelõ {
	public abstract class Személy {

		protected string azonosító;
		protected string bejelentettLakcím;
		protected string név;

		public Személy(){

		}

		~Személy(){

		}

		public virtual void Dispose(){

		}

		public string GetAzonosító(){

			return "";
		}

		public string GetBejelentettLakcím(){

			return "";
		}

		public string GetNév(){

			return "";
		}

	}//end Személy

}//end namespace Adatkezelõ