///////////////////////////////////////////////////////////
//  Személykezelõ.cs
//  Implementation of the Class Személykezelõ
//  Generated by Enterprise Architect
//  Created on:      02-ápr.-2016 10:16:29
//  Original author: gabi1_000
///////////////////////////////////////////////////////////




using Adatkezelõ;
using System.Collections.Generic;
using System.Linq;
using Omra;
using System.Diagnostics;
using System;

namespace Adatkezelõ {
	public class Személykezelõ : IÜzenetkezelõ, IDolgozókezelõ, IGyanúsítottkezelõ
    {
        DatabaseElements DE = new DatabaseElements();

		/// 
		/// <param name="azonosító"></param>
		/// <param name="jelszó"></param>
		public Dolgozó Azonosítás(string felhasználónév, string jelszó)
        {
            Dolgozó dolg = null;
            var talalat = from x in DE.Dolgozok  // kikeresi a megadott felhasználót
                            where x.nev == felhasználónév && x.jelszo == jelszó
                            select x;

            if (talalat.Count() != 0)
            {
                Dolgozok uj = talalat.First();
                dolg = new Dolgozó((Rang)Enum.Parse(typeof(Rang),uj.rang.ToString()), uj.jelszo, uj.nev, uj.lakcim, uj.dolgozoID);
            }

            return dolg; // null-t dob, ha nem létezik ez a dolgozó 
		}

		/// 
		/// <param name="dolgozók"></param>
		public Dolgozó DolgozóKeresés(List<Dolgozó> dolgozók){
            //keresésbe került?
			return null;
		}

		/// 
		/// <param name="dolgozó"></param>
		public void DolgozóMódosítása(Dolgozó dolgozó)
        {
            
		}

		/// 
		/// <param name="Dolgozó"></param>
		public void DolgozóTörlése(Dolgozó Dolgozó)
        {
            
            //------------------------------------------- Adatbázisból törli
		}

		/// 
		/// <param name="Gyanúsított"></param>
		/// <param name="Bûneset"></param>
		public void GyanúsítottHozzáadása(Gyanúsított Gyanúsított, Bûneset Bûneset){
            Bûneset.GyanúsítottHozzáadása(Gyanúsított);
            //---------------------------------Adatbázisban a bûnesetet módosítani
		}

		/// 
		/// <param name="gyanúsított"></param>
		public void GyanúsítottMódosítása(Gyanúsított gyanúsított)
        {
            
		}

		/// 
		/// <param name="jelszó"></param>
		/// <param name="beosztás"></param>
		/// <param name="név"></param>
		/// <param name="azonosító"></param>
		/// <param name="lakcím"></param>
		public void ÚjDolgozó(string jelszó, Rang beosztás, string név, decimal azonosító, string lakcím){

		}

		/// 
		/// <param name="gyanúsítottStátusz"></param>
		/// <param name="lakcím"></param>
		/// <param name="személyiAzonosító"></param>
		/// <param name="név"></param>
		public void ÚjGyanúsított(GyanúsítottStátusz gyanúsítottStátusz, string lakcím, decimal személyiAzonosító, string név){

		}

		/// 
		/// <param name="üzenet"></param>
		public void ÜzenetKüldése(Üzenet üzenet){

		}

		public Üzenet ÜzenetMegtekintése(){

			return null;
		}

		/// 
		/// <param name="üzenet"></param>
		public void ÜzenetTörlése(Üzenet üzenet){

		}


        public void ÜzenetKüldése(string törzs, string tárgy, Dolgozó küldõ, Dolgozó címzett)
        {
            throw new System.NotImplementedException();
        }

        public List<Üzenet> ÜzenetMegtekintése(Dolgozó Dolgozó)
        {
            throw new System.NotImplementedException();
        }
    }//end Személykezelõ

}//end namespace Adatkezelõ