///////////////////////////////////////////////////////////
//  Személy.cs
//  Implementation of the Class Személy
//  Generated by Enterprise Architect
//  Created on:      02-ápr.-2016 10:16:29
//  Original author: gabi1_000
///////////////////////////////////////////////////////////




namespace Adatkezelõ {
	public abstract class Személy {

		protected string azonosító;
		protected string bejelentettLakcím;
		protected string név;

		public Személy(){

		}

		~Személy(){

		}

        public Személy(string azonosító, string lakcím, string név)
        {
            this.azonosító = azonosító;
            this.bejelentettLakcím = lakcím;
            this.név = név;
        }

		public virtual void Dispose(){

		}

		public string GetAzonosító(){

			return this.azonosító;
		}

		public string GetBejelentettLakcím(){

			return this.bejelentettLakcím;
		}

		public string GetNév(){

			return this.név;
		}

	}//end Személy

}//end namespace Adatkezelõ