//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Omra
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uzenetek
    {
        public decimal uzenetID { get; set; }
        public decimal cimzett { get; set; }
        public decimal felado { get; set; }
        public string targy { get; set; }
        public string szoveg { get; set; }
    
        public virtual Dolgozok Dolgozok { get; set; }
        public virtual Dolgozok Dolgozok1 { get; set; }
    }
}
