///////////////////////////////////////////////////////////
//  Üzenetkezelõ.cs
//  Implementation of the Class Üzenetkezelõ
//  Generated by Enterprise Architect
//  Created on:      02-ápr.-2016 10:16:29
//  Original author: Dániel
///////////////////////////////////////////////////////////




using Adatkezelõ;
using Omra;
using System.Collections.Generic;
using System.Linq;
namespace Adatkezelõ {
	public class Üzenetkezelõ : IÜzenetkezelõ {

        DatabaseElements DE = new DatabaseElements();
		/// 
		/// <param name="törzs"></param>
		/// <param name="tárgy"></param>
		/// <param name="küldõ"></param>
		/// <param name="címzett"></param>
		public void ÜzenetKüldése(string törzs, string tárgy, Dolgozó küldõ, Dolgozó címzett){
            
		}

		/// 
		/// <param name="Dolgozó"></param>
		public List<Üzenet> ÜzenetMegtekintése(Dolgozó Dolgozó){

            var uzenetek = from x in DE.Uzenetek
                           where x.cimzett == Dolgozó.GetAzonosító()
                           select x;
		}

		/// 
		/// <param name="üzenet"></param>
		public void ÜzenetTörlése(Üzenet üzenet){

		}

	}//end Üzenetkezelõ

}//end namespace Adatkezelõ