///////////////////////////////////////////////////////////
//  Üzenetkezelõ.cs
//  Implementation of the Class Üzenetkezelõ
//  Generated by Enterprise Architect
//  Created on:      02-ápr.-2016 10:16:29
//  Original author: Dániel
///////////////////////////////////////////////////////////




using Adatkezelõ;
using Omra;
using System;
using System.Collections.Generic;
using System.Linq;
namespace Adatkezelõ {
	public class Üzenetkezelõ : IÜzenetkezelõ {

        DatabaseElements DE = new DatabaseElements();
		/// 
		/// <param name="törzs"></param>
		/// <param name="tárgy"></param>
		/// <param name="küldõ"></param>
		/// <param name="címzett"></param>
		public void ÜzenetKüldése(string törzs, string tárgy, Dolgozó küldõ, Dolgozó címzett)
        {
            var utolsoUzenet = from x in DE.Uzenetek
                               where x.uzenetID == DE.Uzenetek.Last().uzenetID
                               select x.uzenetID;
            decimal kuldoId = küldõ.GetAzonosító();
            decimal cimzettId = címzett.GetAzonosító();
            var ujUzenet = new Uzenetek() { uzenetID = utolsoUzenet.First()+1, szoveg = törzs, targy = tárgy, felado = kuldoId, cimzett = cimzettId };
            DE.Uzenetek.Add(ujUzenet);     // TESZT !!!!!!!!!!!! 
            DE.SaveChanges();
		}

		/// 
		/// <param name="Dolgozó"></param>
		public List<Üzenet> ÜzenetMegtekintése(Dolgozó dolgozo)  // kilistázza a beérklezett üzeneteket
        {
            decimal id = dolgozo.GetAzonosító();    // linq nem szereti ha ott kérem el
            List<Üzenet> vissza = new List<Üzenet>();
            var uzenetek = from x in DE.Uzenetek
                           where x.cimzett == id
                           select x;
            foreach (var item in uzenetek)
            {
                vissza.Add(new Üzenet(item.szoveg,item.targy,KitolJott(item.felado),dolgozo));
            }
            return vissza;
		}

        Dolgozó KitolJott(decimal id)   // létrehoz az üzenetnek egy dolgozó példányt, azt akitõl jött az üzenet
        {
            var kitol = from x in DE.Dolgozok 
                             where x.dolgozoID == id 
                             select x;
            Dolgozok vissza = kitol.First();
            return new Dolgozó((Rang)Enum.Parse(typeof(Rang),vissza.rang.ToString()), vissza.jelszo, vissza.nev, vissza.lakcim, vissza.dolgozoID);
        }

		/// 
		/// <param name="üzenet"></param>
		public void ÜzenetTörlése(Üzenet üzenet)
        {
            decimal id = üzenet.GetUzenetID;
            var aktUzenet = DE.Uzenetek.Single(x => x.uzenetID == id);
            DE.Uzenetek.Remove(aktUzenet);
            DE.SaveChanges();
		}

	}//end Üzenetkezelõ

}//end namespace Adatkezelõ