///////////////////////////////////////////////////////////
//  Üzenet.cs
//  Implementation of the Class Üzenet
//  Generated by Enterprise Architect
//  Created on:      02-ápr.-2016 10:16:29
//  Original author: Dániel
///////////////////////////////////////////////////////////




using Adatkezelõ;
namespace Adatkezelõ {
	public class Üzenet {

		private Dolgozó címzett;
		private Dolgozó küldõ;
		private string tárgy;
		private string törzs;
        
		/// 
		/// <param name="törzs"></param>
		/// <param name="tárgy"></param>
		/// <param name="küldõ"></param>
		/// <param name="címzett"></param>
		public Üzenet(string törzs, string tárgy, Dolgozó küldõ, Dolgozó címzett){
            this.törzs = törzs;
            this.tárgy = tárgy;
            this.küldõ = küldõ;
            this.címzett = címzett;
		}

		public Dolgozó GetCímzett{
			get{
				return címzett;
			}
			set{
				címzett = value;
			}
		}

		public Dolgozó GetKüldõ{
			get{
				return küldõ;
			}
			set{
				küldõ = value;
			}
		}

		public string GetTárgy{
			get{
				return tárgy;
			}
			set{
				tárgy = value;
			}
		}

		public string GetTörzs{
			get{
				return törzs;
			}
			set{
				törzs = value;
			}
		}

	}//end Üzenet

}//end namespace Adatkezelõ